services:
  ubuntu:
    container_name: ubuntu
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - type=gha,mode=max,ignore-error=true
      cache_to:
        - type=gha
