services:
  ubuntu:
    container_name: ubuntu
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - type=local,src=docker-images
      cache_to:
        - type=local,dest=docker-images,mode=max
