services:
  ubuntu:
    container_name: ubuntu
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - type=local,dest=./docker-images
      cache_to:
        - type=local,src=./docker-images,mode=max
