apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    chart: helm-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps/tree/master/helm-guestbook
    targetRevision: 0.1.0
    helm:
      releaseName: guestbook
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
