name: CI

on:
  push:
    branches: [ "master", "r[0-9][0-9].[0-9][0-9]",  "r[0-9][0-9].[0-9]"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
        
      - run: echo $(ls -al) >> $GITHUB_OUTPUT

      - name: Run a one-line script
        env:
          AWS: '{"sample":{"cluster_name":"sample","account_id":"12345"},"sample1":{"cluster_name":"sample1","account_id":"54321"}}'
        run: echo ${{ fromJson(env.AWS).sample.cluster_name }}
