name: CI

on:
  push:
    branches: [ "master", "r[0-9][0-9].[0-9][0-9]",  "r[0-9][0-9].[0-9]"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        id: code
        uses: actions/checkout@v3
        
      - uses: actions/github-script@v6
        id: my-script
        with:
          script: |
            const { data: jobs } = await github.rest.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId
            })
            
            const { data: job } = await github.rest.actions.getJobForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              job_id: jobs.jobs[0].id
            })
            
            console.log(job)
            console.log(job.steps.filter(step => step.name == `'Run terraform init'`)[0])
            console.log(`${jobs.jobs[0].html_url}#step:${number}:1`)
        
      - run: |
          terraform init
          terraform plan >> tfplan 2>&1
          cat tfplan

      - name: Run a one-line script
        env:
          AWS: '{"sample":{"cluster_name":"sample","account_id":"12345"},"sample1":{"cluster_name":"sample1","account_id":"54321"}}'
        run: echo ${{ fromJson(env.AWS).sample.cluster_name }}
