name: Deploy
run-name: Deploy ${{ inputs.sha }}

on:
  workflow_dispatch:
    inputs:
      sha:
        type: string
        required: false

#   workflow_run:
#     workflows:
#       - Build
#     types:
#       - completed
#     branches:
#       - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.sha }}

      - run: echo '${{ toJSON(github.event) }}'
      
      - uses: actions/cache@v3
        with:
          path: docker-images
          key: docker-${{ hashfiles('docker-compose.yml', 'Dockerfile') }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1 
        run: docker compose build
