name: Build

on:
  push:
    branches: [ "master" ]
    
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:
    inputs:
      sample:
        required: true
        type: environment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
        
      - run: |
          echo "###Hi" >> $GITHUB_STEP_SUMMARY
          
      - run: |
          echo "###Hello" >> $GITHUB_STEP_SUMMARY

      - name: Plan
        uses: SanthoshNath/terraform-plan@master
        
      - name: Github event
        env:
          sample: ${{ true && '${{ secrets.SAMPLE }}_fi' || '' }}
        run: |
          echo '${{ env.sample }}'
          echo '${{ toJSON(github.event) }}'

      - name: Run a one-line script
        env:
          AWS: '{"sample":{"cluster_name":"sample","account_id":"12345"},"sample1":{"cluster_name":"sample1","account_id":"54321"}}'
        run: echo ${{ fromJson(env.AWS).sample.cluster_name }}
            
      - uses: actions/github-script@v6
        with:
          script: |
            const { data: commit } = await github.rest.repos.getCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha
            })
            filenames = []
            files = commit.files.filter(file => file.status == 'modified').forEach(file => filenames.push(file.filename))
            console.log(filenames)
