name: Build

on:
  push:
    branches: [ "master" ]
    
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:
    inputs:
      sample:
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
        
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Plan
        uses: SanthoshNath/terraform-plan@v1
        
      - name: Github event
        env:
          sample: ${{ secrets.SAMPLE }}
          sample1: ${{ true && '${sample}_fi' || '' }}
        run: |
          echo ${{ env.sample1 }}
          echo '${{ toJSON(github.event) }}'

      - name: Run a one-line script
        env:
          AWS: '{"sample":{"cluster_name":"sample","account_id":"12345"},"sample1":{"cluster_name":"sample1","account_id":"54321"}}'
        run: echo ${{ fromJson(env.AWS).sample.cluster_name }}
            
      - uses: actions/github-script@v6
        with:
          script: |
            const { data: commit } = await github.rest.repos.getCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha
            })
            filenames = []
            files = commit.files.filter(file => file.status == 'modified').forEach(file => filenames.push(file.filename))
            console.log(filenames)
            
      - run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.token }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type":"deploy","client_payload":{"unit":false,"integration":true}}'
