name: Build

on:
  push:
    branches:
      - master
    
  pull_request:
    branches:
      - master

  workflow_dispatch:
    inputs:
      sample:
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    environment: devl

    steps:
      - uses: actions/github-script@v6
        id: my-script
        with:
          result-encoding: string
          script: |
            await fetch('http://example.com/movies.json').then(
              response => {
                console.log(response)
              }
    
      - name: Checkout codebase
        uses: actions/checkout@v3
        
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Plan
        uses: SanthoshNath/terraform-plan@v1
        
      - name: Github event
        env:
          sample: ${{ secrets.SAMPLE }}
          sample1: ${{ true && '${sample}_fi' || '' }}
        run: |
          echo ${{ env.sample1 }}
          echo '${{ toJSON(github.event) }}'

      - name: Run a one-line script
        env:
          AWS: '{"sample":{"cluster_name":"sample","account_id":"12345"},"sample1":{"cluster_name":"sample1","account_id":"54321"}}'
        run: echo ${{ fromJson(env.AWS).sample.cluster_name }}
            
      - uses: actions/github-script@v6
        with:
          script: |
            const { data: commit } = await github.rest.repos.getCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha
            })
            filenames = []
            files = commit.files.filter(file => file.status == 'modified').forEach(file => filenames.push(file.filename))
            console.log(filenames)
            
  trigger:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            sha_short = context.sha.substr(0, 7)
            
            await github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'CD.yml',
              client_payload: {
                sha: context.sha,
                sha_short: sha_short
              }
            })
