name: Build image

on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/docker.yml"
      - "Dockerfile"
  pull_request:
    branches:
      - "master"
    paths:
      - ".github/workflows/docker.yml"
      - "Dockerfile"

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/santhoshnath/sample:latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: santhoshnath
          password: ${{ github.token }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name == 'push' && 'true' || 'false' }}
          pull: true
          tags: ${{ env.IMAGE_NAME }}
          cache-to: type=gha,ignore-error=true
          cache-from: type=gha
          platforms: linux/amd64,linux/arm64
